# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handshake.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fhandshake.proto\x12\x0c\x63rypto_suite\"\'\n\x0eHandshakeHello\x12\x15\n\rsupported_kem\x18\x05 \x03(\t\"\'\n\x11HandshakeSelected\x12\x12\n\nchosen_kem\x18\x06 \x01(\t*\x18\n\x05\x41lert\x12\x0f\n\x0bNoCommonKEM\x10\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'handshake_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALERT._serialized_start=115
  _ALERT._serialized_end=139
  _HANDSHAKEHELLO._serialized_start=33
  _HANDSHAKEHELLO._serialized_end=72
  _HANDSHAKESELECTED._serialized_start=74
  _HANDSHAKESELECTED._serialized_end=113
# @@protoc_insertion_point(module_scope)
