name: pip-audit

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: pip install -e .[dev]
      - name: pip-audit
        uses: pypa/gh-action-pip-audit@v1
        # Fail the workflow if any vulnerabilities of severity HIGH or greater are found
