name: pip-audit

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: pip install -e .[dev]
      - name: pip-audit
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          ignore-vulns: |
            GHSA-h4gh-qq45-vh27
            GHSA-79v4-65xg-pq4g
        # pip-audit fails the workflow if any non-ignored vulnerabilities are found
