name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  lint:
    name: Static Analysis
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Lint Tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy pylint bandit vulture
          pip install -e .[dev]
      - name: Run flake8
        run: flake8
      - name: Run mypy
        run: mypy cryptography_suite
      - name: Run pylint
        run: pylint --errors-only cryptography_suite || true
      - name: Run bandit
        run: bandit -r cryptography_suite --exit-zero || true
      - name: Run vulture
        run: vulture cryptography_suite tests || true

  doctest:
    name: README Doctest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run doctests on README
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          python -m doctest README.md

  tests:
    name: Unit Tests (Matrix)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Test Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pytest pytest-cov coverage mypy hypothesis
      - name: Run Tests with Coverage
        run: |
          coverage run --rcfile=.coveragerc -m pytest
          coverage xml
      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.xml
          flag-name: OS-${{ matrix.os }}-py${{ matrix.python-version }}
          parallel: true

  tests-extras:
    name: Tests (With Extras)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Full Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pqcrypto pybulletproofs
          pip install Pyfhel || echo "⚠️ Pyfhel build failed"
          pip install pytest pytest-cov coverage mypy hypothesis
      - name: Run Extended Tests
        run: |
          coverage run --rcfile=.coveragerc -m pytest
          coverage xml
      - name: Upload Extended Coverage to Coveralls
        uses: coverallsapp/github-action@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.xml
          flag-name: extras
          parallel: true

  coveralls:
    name: Finalize Coverage Merge
    needs: [tests, tests-extras]
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Parallel Coverage
        uses: coverallsapp/github-action@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
