name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Generate full coverage tests
        run: |
          coverage run -m pytest || true
          coverage xml -i
          python tools/make_full_coverage.py
      - name: Run tests
        run: coverage run -m pytest
      - name: Coverage gate
        run: |
          coverage xml
          python - <<'PY'
          import xml.etree.ElementTree as ET, sys
          root = ET.parse('coverage.xml').getroot()
          rate = float(root.attrib['line-rate'])
          delta = float(root.attrib.get('line-rate-delta', '0'))
          sys.exit(0 if rate == 1.0 and delta >= 0 else 1)
          PY
